### ISSUE TITLE
Access to openstack EC2 API 

### ISSUE THREAD

**Issue by kosmasgiannis** [chilts/awssum-amazon-ec2#1]
Hi there,

I am wondering if it is possible to access an openstack cloud via its EC2 API using awssum-amazon-ec2 and awssum-amazon-s3 plugins.

Has anyone made any such experiment?

**Comment by chilts** [comment]
No, this isn't possible I don't think.

I have been trying to add changes to AwsSum for a while now whereby you could give it a new hostname, port and perhaps even a path in the constructor, but it's never been finished or tested.

**Comment by chilts** [comment]
(deprecated: use aws-sdk)
